server {
    listen 80;
    
    # Where Nginx looks for the files
    root /usr/share/nginx/html;
    index index.html;

    # This fixes the 404 Refresh bug!
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optional: Cache static assets for better performance
    location ~* \.(?:css|js|jpg|svg|png)$ {
        expires 1y;
        add_header Cache-Control "public";
    }
}