server:
  port: 8084
  servlet:
    context-path: /notification-service

spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: 
  rabbitmq:
    host: 
    port: 
    username: 
    password: 
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: your_mailtrap_user
    password: your_mailtrap_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
