version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: syncclinic-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword123
      POSTGRES_DB: syncclinic_auth
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  # ... your existing postgres databases are up here ...

  kafka:
    image: confluentinc/confluent-local:7.6.0
    container_name: syncclinic_broker
    ports:
      - "9092:9092"
    environment:
      # This tells Kafka to run in KRaft mode (No Zookeeper required!)
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

volumes:
  postgres-data: