server.port=8084

spring.application.name=payment-service

# PostgreSQL - uses its own database
spring.datasource.url=jdbc:postgresql://postgres-payment-db:5432/syncclinic_payment
spring.datasource.username=postgres
spring.datasource.password=rootpassword123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Eureka
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/
eureka.instance.prefer-ip-address=true

# Stripe (replace with your own sandbox keys from dashboard.stripe.com)
stripe.api.key=${STRIPE_API_KEY:sk_test_51TMRVCRx3TiIWi21ORiqn4uExXI1WfMowDiuOBnNSWkoymXFSJP6m9kCHATnA70b3wand56OSQdqUDIQ7Efb1g9i00kO3v2T8x}
stripe.publishable.key=${STRIPE_PUBLISHABLE_KEY:pk_test_51TMRVCRx3TiIWi21sogS8kzWtI2BKfk1x1uTgsnV526Ud5Y5JPLvdvkV24O1g5BmVrjIfUELgdZefrn9pgEUqVTW001VxdRF2Q}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET:whsec_331095c6936e568759b2a0556aa2e04d721e4adef4e38de827c9b4a7ebe259a3}
jwt.secret=${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}

# Kafka Topics
kafka.topic.payment-success=payment-success-events
kafka.topic.payment-failed=payment-failed-events

# Logging
logging.level.com.syncclinic.paymentservice=DEBUG