server.port=8084

spring.application.name=payment-service

# PostgreSQL - uses its own database
spring.datasource.url=jdbc:postgresql://localhost:5435/syncclinic_payment
spring.datasource.username=postgres
spring.datasource.password=rootpassword123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Stripe (replace with your own sandbox keys from dashboard.stripe.com)
stripe.api.key=sk_test_placeholder
stripe.webhook.secret=whsec_placeholder
jwt.secret=dGVzdHNlY3JldGtleXRoYXRpc2xvbmdlbm91Z2hmb3Ioand0

# Kafka Topics
kafka.topic.payment-success=payment-success-events
kafka.topic.payment-failed=payment-failed-events

# Logging
logging.level.com.syncclinic.paymentservice=DEBUG