# ==========================================
# DOCTOR SERVICE
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-service
  template:
    metadata:
      labels:
        app: doctor-service
    spec:
      containers:
      - name: doctor-service
        image: syncclinic-doctor-service:v1 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-db:5432/syncclinic_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: syncclinic-secrets
              key: POSTGRES_PASSWORD
        - name: EUREKA_CLIENT_ENABLED
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: doctor-service
spec:
  selector:
    app: doctor-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083

---
# ==========================================
# APPOINTMENT SERVICE
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-service
        image: syncclinic-appointment-service:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8084
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-db:5432/syncclinic_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: syncclinic-secrets
              key: POSTGRES_PASSWORD
        - name: EUREKA_CLIENT_ENABLED
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
spec:
  selector:
    app: appointment-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084

---
# ==========================================
# NOTIFICATION SERVICE
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: syncclinic-notification-service:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8085
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-db:5432/syncclinic_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: syncclinic-secrets
              key: POSTGRES_PASSWORD
        - name: EUREKA_CLIENT_ENABLED
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085