server:
  port: ${SERVER_PORT:8088}

spring:
  application:
    name: medisphere-AIsymptomcheck-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/ai_symptoms_db}
    driverClassName: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:rootpassword123}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info}

eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:false}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}

openai:
  api-url: https://api.openai.com/v1/chat/completions
  api-key: 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
  model: gpt-4o-mini

jwt:
  secret: ${JWT_SECRET:your_very_secure_and_long_secret_key_for_medisphere_telemedicine_service_2026}

logging:
  level:
    com:
      medisphere: DEBUG