apiVersion: v1
kind: Secret
metadata:
  name: syncclinic-secrets
type: Opaque
stringData:
  # stringData lets you type raw text, and K8s will encrypt it behind the scenes
  POSTGRES_PASSWORD: "rootpassword123"
  OPENAI_API_KEY: "sk-proj-your-new-real-key-here"
